# Generated by Django 3.2.7 on 2021-12-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='user_profile_pic/avatar.png', upload_to='user_profile_pic'),
        ),
    ]
