# Generated by Django 3.2.7 on 2021-12-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceplan',
            name='plan_image',
            field=models.ImageField(null=True, upload_to='Subscription/'),
        ),
    ]
