# Generated by Django 3.2.7 on 2021-12-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
    ]
