# Generated by Django 3.2.7 on 2021-12-09 05:57

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0015_alter_doctorschedule_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=500)),
                ('ammount', models.FloatField(max_length=100)),
                ('card_type', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('transaction_date', models.CharField(max_length=100)),
                ('risk_title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(max_length=200, null=True)),
                ('patient_name', models.CharField(max_length=1000)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Other', 'Other'), ('Male', 'Male')], default='Male', max_length=100)),
                ('age', models.IntegerField()),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=50)),
                ('problem_brief', ckeditor.fields.RichTextField()),
                ('appointment_time', models.TimeField(null=True)),
                ('appointment_date', models.DateField(null=True)),
                ('appointment_type', models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], default='Online', max_length=100)),
                ('confirmation_status', models.CharField(choices=[('Reject', 'Reject'), ('Pending', 'Pending'), ('Accept', 'Accept')], default='Pending', max_length=100)),
                ('pay_status', models.BooleanField(default=False, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.paymentdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
