# Generated by Django 3.2.7 on 2021-12-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='confirmation_status',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Pending', 'Pending'), ('Reject', 'Reject')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='gender',
            field=models.CharField(choices=[('Other', 'Other'), ('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=100),
        ),
    ]
