# Generated by Django 3.2.7 on 2021-12-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20211210_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='ammount',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='confirmation_status',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='gender',
            field=models.CharField(choices=[('Other', 'Other'), ('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=100),
        ),
    ]
