# Generated by Django 3.2.7 on 2021-12-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_auto_20211216_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], default='Online', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='confirmation_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reject', 'Reject'), ('Accept', 'Accept')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=100),
        ),
    ]
