# Generated by Django 3.2.7 on 2021-11-01 20:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='test_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
