# Generated by Django 3.2.7 on 2021-11-01 21:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_test_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='test_content',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
