# Generated by Django 3.2.7 on 2021-12-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211102_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='Blog_images/'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
