# Generated by Django 3.2.7 on 2021-12-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pecelife', '0006_frequentlyquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequentlyquestion',
            old_name='qustion',
            new_name='questions',
        ),
    ]
