# Generated by Django 3.2.7 on 2021-12-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pecelife', '0007_rename_qustion_frequentlyquestion_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequentlyquestion',
            old_name='questions',
            new_name='question',
        ),
    ]
