# Generated by Django 3.2.7 on 2021-12-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctorschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='day',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Friday ', 'Friday '), ('Thursday', 'Thursday'), ('Sunday', 'Sunday'), ('Monday', 'Monday')], default='Saturday', max_length=100),
        ),
    ]
