# Generated by Django 3.2.7 on 2021-12-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctorschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='day',
            field=models.CharField(choices=[('Thursday', 'Thursday'), ('Monday', 'Monday'), ('Wednesday', 'Wednesday'), ('Friday ', 'Friday '), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Tuesday', 'Tuesday')], default='Saturday', max_length=100),
        ),
    ]
