# Generated by Django 3.2.7 on 2021-12-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_doctorschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='day',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Thursday', 'Thursday'), ('Monday', 'Monday'), ('Wednesday', 'Wednesday'), ('Tuesday', 'Tuesday'), ('Friday ', 'Friday '), ('Sunday', 'Sunday')], default='Saturday', max_length=100),
        ),
    ]
