# Generated by Django 3.2.7 on 2021-12-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_doctorschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='day',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Sunday', 'Sunday'), ('Thursday', 'Thursday'), ('Friday ', 'Friday '), ('Wednesday', 'Wednesday')], default='Saturday', max_length=100),
        ),
    ]
