# Generated by Django 3.2.7 on 2021-12-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_alter_doctorschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Friday ', 'Friday '), ('Thursday', 'Thursday'), ('Sunday', 'Sunday'), ('Wednesday', 'Wednesday'), ('Saturday', 'Saturday')], default='Saturday', max_length=100),
        ),
    ]
