# Generated by Django 3.2.7 on 2021-12-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_alter_doctorschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='day',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Friday ', 'Friday '), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Tuesday', 'Tuesday'), ('Monday', 'Monday')], default='Saturday', max_length=100),
        ),
    ]
