# Generated by Django 3.2.7 on 2021-12-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_alter_doctorschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='day',
            field=models.CharField(choices=[('Thursday', 'Thursday'), ('Monday', 'Monday'), ('Sunday', 'Sunday'), ('Tuesday', 'Tuesday'), ('Friday ', 'Friday '), ('Wednesday', 'Wednesday'), ('Saturday', 'Saturday')], default='Saturday', max_length=100),
        ),
    ]
