# Generated by Django 3.2.7 on 2021-12-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_alter_doctorschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday ', 'Friday '), ('Sunday', 'Sunday'), ('Saturday', 'Saturday'), ('Tuesday', 'Tuesday')], default='Saturday', max_length=100),
        ),
    ]
