# Generated by Django 3.2.7 on 2021-12-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_alter_doctorschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='day',
            field=models.CharField(choices=[('Tuesday', 'Tuesday'), ('Sunday', 'Sunday'), ('Saturday', 'Saturday'), ('Thursday', 'Thursday'), ('Friday ', 'Friday '), ('Wednesday', 'Wednesday'), ('Monday', 'Monday')], default='Saturday', max_length=100),
        ),
    ]
