# Generated by Django 3.2.7 on 2021-12-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_alter_doctorschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Tuesday', 'Tuesday'), ('Friday ', 'Friday '), ('Monday', 'Monday'), ('Wednesday', 'Wednesday'), ('Saturday', 'Saturday'), ('Thursday', 'Thursday')], default='Saturday', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
