# Generated by Django 3.2.7 on 2021-12-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_auto_20211210_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='day',
            field=models.CharField(choices=[('Friday ', 'Friday '), ('Thursday', 'Thursday'), ('Monday', 'Monday'), ('Sunday', 'Sunday'), ('Wednesday', 'Wednesday'), ('Saturday', 'Saturday'), ('Tuesday', 'Tuesday')], default='Saturday', max_length=100),
        ),
    ]
