# Generated by Django 3.2.7 on 2021-12-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_alter_doctorschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Saturday', 'Saturday'), ('Friday ', 'Friday '), ('Tuesday', 'Tuesday'), ('Sunday', 'Sunday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday')], default='Saturday', max_length=100),
        ),
    ]
