# Generated by Django 3.2.7 on 2021-12-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0019_alter_doctorschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='day',
            field=models.CharField(choices=[('Wednesday', 'Wednesday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Thursday', 'Thursday'), ('Friday ', 'Friday '), ('Sunday', 'Sunday'), ('Saturday', 'Saturday')], default='Saturday', max_length=100),
        ),
    ]
