# Generated by Django 3.2.7 on 2021-12-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_alter_doctorschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='day',
            field=models.CharField(choices=[('Friday ', 'Friday '), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Saturday', max_length=100),
        ),
    ]
